I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 109, in script
    show turan mad moveoutleft
Exception: Image 'turan mad' does not accept attributes 'moveoutleft'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 109, in script
    show turan mad moveoutleft
  File "C:\Users\Karely\Desktop\renpy-8.3.2-sdk\renpy\ast.py", line 1111, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Karely\Desktop\renpy-8.3.2-sdk\renpy\ast.py", line 1074, in show_imspec
    renpy.config.show(name,
  File "C:\Users\Karely\Desktop\renpy-8.3.2-sdk\renpy\exports\displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\Karely\Desktop\renpy-8.3.2-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\Karely\Desktop\renpy-8.3.2-sdk\renpy\display\displayable.py", line 249, in _duplicate
    args.extraneous()
  File "C:\Users\Karely\Desktop\renpy-8.3.2-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'turan mad' does not accept attributes 'moveoutleft'.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.2.24090902
O Coco Taco The Visual Novel The Game 1.0
Tue Feb  4 19:15:54 2025
