I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 34, in script
    show turan sad at third_left with move
  File "game/script.rpy", line 34, in <module>
    show turan sad at third_left with move
NameError: name 'third_left' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 34, in script
    show turan sad at third_left with move
  File "/Applications/renpy-8.1.3-sdk/renpy/ast.py", line 1113, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/Applications/renpy-8.1.3-sdk/renpy/ast.py", line 1072, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "/Applications/renpy-8.1.3-sdk/renpy/ast.py", line 1072, in <listcomp>
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "/Applications/renpy-8.1.3-sdk/renpy/python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Applications/renpy-8.1.3-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 34, in <module>
    show turan sad at third_left with move
NameError: name 'third_left' is not defined

macOS-15.1.1-arm64-arm-64bit arm64
Ren'Py 8.2.1.24030407
O Coco Taco The Visual Novel The Game 1.0
Mon Feb  3 20:13:15 2025
