I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 28, in script
    DJ "You've created a new Ren'Py game.  crunch wrap supreme 😿"
Exception: Sayer 'DJ' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 28, in script
    DJ "You've created a new Ren'Py game.  crunch wrap supreme 😿"
  File "/Applications/renpy-8.1.3-sdk/renpy/ast.py", line 2557, in execute
    Say.execute(self)
  File "/Applications/renpy-8.1.3-sdk/renpy/ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Applications/renpy-8.1.3-sdk/renpy/ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'DJ' is not defined.

macOS-15.1.1-arm64-arm-64bit arm64
Ren'Py 8.2.1.24030407
O Coco Taco The Visual Novel The Game 1.0
Fri Jan 24 12:39:28 2025
